local utils = require("utils")

utils.load_plugins({
    { src = "https://github.com/rose-pine/neovim", name = "rose-pine" },
    { src = 'https://github.com/saghen/blink.lib' },
    { src = 'https://github.com/Saghen/blink.cmp' },
    { src = 'https://github.com/rafamadriz/friendly-snippets' },
    { src = 'https://github.com/folke/flash.nvim' },
    { src = 'https://github.com/nvim-telescope/telescope.nvim' },
    { src = 'https://github.com/nvim-telescope/telescope-ui-select.nvim' },
    { src = 'https://github.com/lewis6991/gitsigns.nvim' },
    { src = 'https://github.com/windwp/nvim-ts-autotag' },
    { src = 'https://github.com/smjonas/inc-rename.nvim' },
    { src = 'https://github.com/kdheepak/lazygit.nvim' },
    { src = 'https://github.com/nvim-lualine/lualine.nvim' },
    { src = 'https://github.com/neovim/nvim-lspconfig' },
    { src = 'https://github.com/mason-org/mason.nvim' },
    { src = 'https://github.com/williamboman/mason-lspconfig.nvim' },
    { src = 'https://github.com/jay-babu/mason-nvim-dap.nvim' },
    { src = 'https://github.com/nvim-mini/mini.bufremove' },
    { src = 'https://github.com/nvim-mini/mini.pairs' },
    { src = 'https://github.com/nvim-mini/mini.surround' },
    { src = 'https://github.com/echasnovski/mini.extra' },
    { src = 'https://github.com/echasnovski/mini.ai' },
    { src = 'https://github.com/nvim-treesitter/nvim-treesitter-textobjects' },
    { src = 'https://github.com/folke/noice.nvim' },
    { src = 'https://github.com/MunifTanjim/nui.nvim' },
    { src = 'https://github.com/mfussenegger/nvim-dap' },
    { src = 'https://github.com/igorlfs/nvim-dap-view' },
    { src = "https://github.com/romus204/tree-sitter-manager.nvim" },
    { src = "https://github.com/stevearc/conform.nvim" },
    { src = "https://github.com/nvim-lua/plenary.nvim" },
    { src = "https://github.com/theprimeagen/harpoon", version = "harpoon2" },
    { src = "https://github.com/nvim-tree/nvim-web-devicons" },
    { src = "https://github.com/b0o/incline.nvim" },
    { src = "https://github.com/abecodes/tabout.nvim" },
    { src = 'https://github.com/nvim-neo-tree/neo-tree.nvim' },
    { src = 'https://github.com/wansmer/treesj' },
})
